import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import Header from '@/components/Header';
import { db } from '@/db_connection';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='dracula'>
      <body className={inter.className + ' flex flex-col bg-base-300'}>
        <Header />
        <main className='container mx-auto flex min-h-[calc(100svh-4rem)] flex-1 flex-col items-center'>
          {children}
        </main>
      </body>
    </html>
  );
}
