name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: ./
          outPath: ./deploy.tar

      - name: Deploy the tar to caprover
        uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.WEB_APP_NAME }}'
          token: '${{ secrets.WEB_APP_TOKEN }}'
