name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & deplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: ./
          outPath: ./deploy.tar

      - name: List files
        run: ls -l

      - name: PWD
        run: pwd

      - name: Deploy the tar to caprover
        uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
